version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.7 # Utiliza la versi贸n de Docker que prefieras
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Utiliza la versi贸n de Docker que prefieras

  deploy:
    docker:
      - image: docker:20.10.7 # Utiliza la versi贸n de Docker que prefieras
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7 # Utiliza la versi贸n de Docker que prefieras
      - run:
          name: Construir y enviar imagen de Docker a Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker build -t circleci:latest .
            docker image tag circleci:latest mattriches/circleci:latest
            docker image push mattriches/circleci:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
